image: yourlabs/ansible

qa:
  stage: test
  script: flake8 --ignore=N806,E704,W503 src  --exclude src/flow2/flow2/__init__.py

pytest:
  stage: test
  script:
  - pip install --user madbg src/cli2[test] src/template2 src/flow2 src/prompt2 src/chttpx src/cansible litellm
  - unset DEBUG && pytest -vvs --cov cli2 --cov-report=xml:coverage.xml --junitxml=report.xml --cov-report=term-missing --strict tests
  - CI_PROJECT_PATH=yourlabs/cli2 CI_BUILD_REPO=https://github.com/yourlabs/cli2 codecov-bash -f coverage.xml
  artifacts:
    reports:
      junit: report.xml

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]

packages:
  stage: deploy
  only: [tags]
  script: cd src/$CI_JOB_NAME && pypi-release TWINE_PASSWORD_${CI_JOB_NAME}
  parallel:
    matrix:
      - CI_JOB_NAME:
        - cansible
        - chttpx
        - template2
        - prompt2
        - flow2
