image: yourlabs/ansible

qa:
  stage: test
  script: flake8 --ignore=N806,E704,W503 cli2

pytest:
  stage: test
  script:
  - pip install --user -e .[client,test]
  - unset DEBUG && pytest -vv --cov cli2 --cov-report=xml:coverage.xml --junitxml=report.xml --cov-report=term-missing --strict
  - CI_PROJECT_PATH=yourlabs/cli2 CI_BUILD_REPO=https://github.com/yourlabs/cli2 codecov-bash -f coverage.xml
  artifacts:
    reports:
      junit: report.xml

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]

pypi-pytest-cli2-ansible:
  stage: deploy
  script: cd pytest-cli2-ansible && pypi-release
  only: [tags]
