qa:
  stage: test
  image: yourlabs/python
  script: flake8 djcli.py test_djcli.py conftest.py

test:
  stage: test
  image: yourlabs/python
  script: pip install django . && py.test -v

pypi:
  stage: deploy
  image: yourlabs/python
  script: pypi-release
