image: yourlabs/ansible

qa:
  stage: test
  script: flake8 --ignore=N806,E704,W503 cli2 chttpx cansible

pytest:
  stage: test
  script:
  - pip install --user -e .[test] -e chttpx -e cansible -e prompt2 -e code2 -e flow2 -e template2 litellm
  - unset DEBUG && pytest -vv --cov cli2 --cov-report=xml:coverage.xml --junitxml=report.xml --cov-report=term-missing --strict
  - CI_PROJECT_PATH=yourlabs/cli2 CI_BUILD_REPO=https://github.com/yourlabs/cli2 codecov-bash -f coverage.xml
  artifacts:
    reports:
      junit: report.xml

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]

packages:
  stage: deploy
  only: [tags]
  script: cd $CI_JOB_NAME && pypi-release TWINE_PASSWORD_${CI_JOB_NAME}
  parallel:
    matrix:
      - CI_JOB_NAME:
        - cansible
        - chttpx
        - code2
        - prompt2
        - flow2
