image: yourlabs/python

qa:
  stage: test
  script: flake8

pytest:
  stage: test
  script:
  - pip install --user -e .
  - pytest -vv --cov cli2 --cov-report=xml:coverage.xml --cov-report=term-missing --strict
  - codecov-bash -f coverage.xml

pypi:
  stage: deploy
  script: pypi-release
