image: yourlabs/python

qa:
  stage: test
  script: pip install -e git+https://gitlab.com/pycqa/flake8.git#egg=flake8 flake8

pytest:
  stage: test
  script:
  - pip install --user -e .
  - pytest -vv --cov cli2 --cov-report=xml:coverage.xml --junitxml=report.xml --cov-report=term-missing --strict
  - CI_PROJECT_PATH=yourlabs/cli2 CI_BUILD_REPO=https://github.com/yourlabs/cli2 codecov-bash -f coverage.xml
  artifacts:
    reports:
      junit: report.xml

pypi:
  stage: deploy
  script: pypi-release
