version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
  - method: pip
    path: src/cli2
    extra_requirements: [test,httpx,ansible]
  - method: pip
    path: src/prompt2
  - method: pip
    path: src/flow2
  - method: pip
    path: src/template2
  - method: pip
    path: src/chttpx
  - method: pip
    path: src/cansible
  - method: pip
    name: litellm
  - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
