version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
  - method: pip
    path: .
    extra_requirements: [test,httpx,ansible]
  - method: pip
    path: code2
  - method: pip
    path: prompt2
  - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
